fragment MainPageParts on MainPage {
  blocks {
    __typename
    ... on MainPageBlocksLargeHero {
      headline
      richHook
      popupVideoActive
      popupVideoButtonLabel
      popupVideoButtonSource
      serviceBarActive
      videoBackgroundActive
      backgroundVideoSource
      backgroundImageSourceDesktop
      backgroundImageAltDesktop
      desktopBackgroundPosition
      backgroundImageSourceMobile
      backgroundImageAltMobile
    }
    ... on MainPageBlocksHero {
      subHeadline
      headline
      hook
      backgroundImage
      desktopBackgroundPosition
      backgroundImageMobile
      backgroundImageAlt
      ctaActive
      ctaLabel
      ctaHref
    }
    ... on MainPageBlocksLongFeaturedImage {
      standardSubHeadline
      standardHeadline
      twoColumnText
      featuredImage {
        __typename
        image
        title
        imagePosition
      }
      featuredImageRightActive
      blocks {
        __typename
        ... on MainPageBlocksLongFeaturedImageBlocksCenteredIconBlurb {
          icon
          iconAlt
          text
        }
        ... on MainPageBlocksLongFeaturedImageBlocksIconListBlurb {
          iconList {
            __typename
            title
            icon
          }
          text
        }
        ... on MainPageBlocksLongFeaturedImageBlocksButton {
          label
          href
        }
        ... on MainPageBlocksLongFeaturedImageBlocksTitledIconBlurb {
          icon
          iconAlt
          Headline
          subHeadline
          blurb
        }
        ... on MainPageBlocksLongFeaturedImageBlocksCursiveHeadline {
          headline
        }
      }
      backgroundColor
      bottomPaddingActive
    }
    ... on MainPageBlocksCtaButtons {
      mainCallToActionLabel
      mainCallToActionHref
      secondaryCallToActionLabel
      secondaryCallToActionVideoActive
      secondaryCallToActionHrefOrSource
      backgroundColor
    }
    ... on MainPageBlocksShortIconGrid {
      headline
      featuredIconBlurb {
        __typename
        title
        icon
        blurb
      }
    }
    ... on MainPageBlocksTestimonialSlider {
      standardSubHeadline
      standardHeadline
    }
    ... on MainPageBlocksPreFooterCta {
      standardSubHeadline
      standardHeadline
      hook
      mainCallToActionLabel
      mainCallToActionHref
    }
    ... on MainPageBlocksPricingTable {
      standardSubHeadline
      standardHeadline
      tableSections {
        __typename
        title
        tables {
          __typename
          title
          price
          description
          attention
          ctaLabel
          ctaHref
          features {
            __typename
            title
          }
        }
      }
    }
    ... on MainPageBlocksFeaturedIconGrid {
      standardSubHeadline
      standardHeadline
      backgroundImageSrc
      maxColumns
      iconSections {
        __typename
        title
        icon
      }
    }
  }
  seo {
    __typename
    title
    description
    image
    noFollow
    noIndex
  }
  mapEnabled
}

fragment ContactParts on Contact {
  subHeadline
  headline
  hook
  backgroundImage
  desktopBackgroundPosition
  backgroundImageAlt
  backgroundImageMobile
  seo {
    __typename
    title
    description
    image
    noFollow
    noIndex
  }
}

fragment GlobalParts on Global {
  header {
    __typename
    preHeaderCtaLabel
    preHeaderCtaHref
    links {
      __typename
      title
      href
    }
    ctaLabel
    ctaHref
  }
  businessInfo {
    __typename
    contact {
      __typename
      phone
      address
      email
    }
    hours {
      __typename
      monday
      tuesday
      wednesday
      thursday
      friday
      saturday
      sunday
    }
    socialLinks {
      __typename
      facebook
      instagram
      youtube
      maps
      tiktok
    }
  }
  services {
    __typename
    title
    serviceBarImage
  }
  testimonials {
    __typename
    testimonialsList {
      __typename
      title
      shortDescription
      image
      imageAlt
      testimonialBody
      activePages {
        __typename
        title {
          ... on Document {
            id
          }
        }
        priority
      }
      videoActive
      videoSource
    }
  }
  events {
    __typename
    eventList {
      __typename
      title
      toggleDates
      date
      toggleEndDates
      endDate
      eventLogos {
        __typename
        title
        logo
      }
      description
      ctaLabel
      ctaHref
    }
  }
  camps {
    __typename
    campList {
      __typename
      title
      date
      dateEnd
      description
      ctaLabel
      ctaHref
    }
  }
}

fragment LegalParts on Legal {
  legalPageTitle
  body
  seo {
    __typename
    title
    description
    image
    noFollow
    noIndex
  }
}
